CREATE TABLE IF NOT EXISTS person_cnd (
	id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	person_id INTEGER UNIQUE NOT NULL REFERENCES person(id),
	certificate_number TEXT NOT NULL,
	exp_date TIMESTAMP WITH TIME ZONE NOT NULL,
	meta JSONB
);
