CREATE TABLE IF NOT EXISTS nfe_farm_cnd (
	id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	farm_id INTEGER UNIQUE NOT NULL REFERENCES farm(id),
	certificate_number TEXT NOT NULL,
	exp_date TIMESTAMP WITH TIME ZONE NOT NULL,
	meta JSONB
);
