-- 000025_cfop_catalog.sql
--
-- System-wide CFOP catalog + farm-tied CFOPs + per-farm use counters for the
-- detached NF-e (NF-e avulsa) selector.
--
-- * cfop: read-only reference catalog, seeded from the Contabilizei complete
--   CFOP table (https://www.contabilizei.com.br/contabilidade-online/tabela-cfop-completa/)
--   plus the CFOPs already assumed by the system (pkg/nfe/defaults
--   NaturezaOpForCFOP keys and the agriculture defaults 5101/5102/5901/6202).
-- * farm_cfop: farm-registered extra codes. Disjoint from cfop (registration
--   rejects catalog duplicates), visible only to the owning farm.
-- * farm_cfop_use: per-farm use counters feeding the "Mais utilizados" group.
--   Local DB only; never sent to SEFAZ.
--
-- origin_destination is derived from the first digit (1/5 = Mesmo estado,
-- 2/6 = Outro estado, 3/7 = Exterior). The referenced page lists 6905 with
-- "Mesmo estado"; it is seeded as "Outro estado" to match the derivation rule.
--
-- Idempotent: CREATE TABLE IF NOT EXISTS + INSERT ... ON CONFLICT DO NOTHING.

CREATE TABLE IF NOT EXISTS cfop (
    code               TEXT PRIMARY KEY,
    description        TEXT NOT NULL,
    origin_destination TEXT NOT NULL,
    CONSTRAINT cfop_origin_destination_check
        CHECK (origin_destination IN ('Mesmo estado', 'Outro estado', 'Exterior'))
);

CREATE TABLE IF NOT EXISTS farm_cfop (
    farm_id            INTEGER NOT NULL REFERENCES farm(id),
    code               TEXT    NOT NULL,
    description        TEXT    NOT NULL,
    origin_destination TEXT    NOT NULL,
    PRIMARY KEY (farm_id, code),
    CONSTRAINT farm_cfop_origin_destination_check
        CHECK (origin_destination IN ('Mesmo estado', 'Outro estado', 'Exterior'))
);

CREATE TABLE IF NOT EXISTS farm_cfop_use (
    farm_id    INTEGER NOT NULL REFERENCES farm(id),
    code       TEXT    NOT NULL,
    use_count  INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (farm_id, code)
);

INSERT INTO cfop (code, description, origin_destination) VALUES
    ('1101', 'Venda de produção do estabelecimento', 'Mesmo estado'),
    ('1102', 'Compra para comercialização', 'Mesmo estado'),
    ('1103', 'Venda de produção do estabelecimento ao contribuinte do ICMS', 'Mesmo estado'),
    ('1104', 'Venda de produção do estabelecimento a não contribuinte', 'Mesmo estado'),
    ('1152', 'Transferência de produtos de outro estabelecimento da mesma empresa, para serem comercializadas', 'Mesmo estado'),
    ('1154', 'Transferência para utilização na prestação de serviço de outro estabelecimento da mesma empresa, para serem utilizadas nas prestações de serviços', 'Mesmo estado'),
    ('1202', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros', 'Mesmo estado'),
    ('1204', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', 'Mesmo estado'),
    ('1209', 'Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência', 'Mesmo estado'),
    ('1409', 'Transferência para comercialização em operação com mercadoria sujeita ao regime de substituição tributária, para serem comercializadas, decorrentes de operações sujeitas ao regime de substituição tributária', 'Mesmo estado'),
    ('1411', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária', 'Mesmo estado'),
    ('1415', 'Retorno de mercadoria adquirida ou recebida de terceiros, remetida para venda fora do estabelecimento em operação com mercadoria sujeita ao regime de substituição tributária', 'Mesmo estado'),
    ('1552', 'Transferência de bem do ativo imobilizado recebidos em transferência de outro estabelecimento da mesma empresa', 'Mesmo estado'),
    ('1553', 'Devolução de venda de bem do ativo imobilizado', 'Mesmo estado'),
    ('1554', 'Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento', 'Mesmo estado'),
    ('1555', 'Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento', 'Mesmo estado'),
    ('1557', 'Transferência de material para uso ou consumo recebidos em transferência de outro estabelecimento da mesma empresa', 'Mesmo estado'),
    ('1901', 'Remessa para industrialização', 'Mesmo estado'),
    ('1904', 'Retorno de remessa para venda fora do estabelecimento', 'Mesmo estado'),
    ('1906', 'Retorno de mercadoria remetida para depósito fechado ou armazém geral', 'Mesmo estado'),
    ('1907', 'Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral', 'Mesmo estado'),
    ('1908', 'Entrada de bem por conta de contrato de comodatoo', 'Mesmo estado'),
    ('1909', 'Retorno de bem remetido por conta de contrato de comodato', 'Mesmo estado'),
    ('1912', 'Entrada de mercadoria ou bem recebido para demonstração ou mostruário', 'Mesmo estado'),
    ('1913', 'Retorno de mercadoria ou bem remetido para demonstração, mostruário ou treinamento', 'Mesmo estado'),
    ('1914', 'Retorno de mercadoria ou bem remetido para exposição ou feira', 'Mesmo estado'),
    ('1915', 'Entrada de mercadoria ou bem recebido para conserto ou reparo', 'Mesmo estado'),
    ('1916', 'Retorno de mercadoria ou bem remetido para conserto ou reparo', 'Mesmo estado'),
    ('1917', 'Entrada de mercadoria recebida em consignação mercantil ou industrial', 'Mesmo estado'),
    ('1918', 'Devolução de mercadoria remetida em consignação mercantil ou industrial', 'Mesmo estado'),
    ('1925', 'Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente', 'Mesmo estado'),
    ('1949', 'Outra entrada de mercadoria ou prestação de serviço não especificada', 'Mesmo estado'),
    ('2102', 'Compra para comercialização', 'Outro estado'),
    ('2152', 'Transferência de produtos de outro estabelecimento da mesma empresa, para serem comercializadas', 'Outro estado'),
    ('2154', 'Transferência para utilização na prestação de serviço de outro estabelecimento da mesma empresa, para serem utilizadas nas prestações de serviços', 'Outro estado'),
    ('2202', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros', 'Outro estado'),
    ('2204', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', 'Outro estado'),
    ('2209', 'Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência', 'Outro estado'),
    ('2403', 'Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária', 'Outro estado'),
    ('2409', 'Transferência para comercialização em operação com mercadoria sujeita ao regime de substituição tributária, para serem comercializadas, decorrentes de operações sujeitas ao regime de substituição tributária', 'Outro estado'),
    ('2411', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária', 'Outro estado'),
    ('2415', 'Retorno de mercadoria adquirida ou recebida de terceiros, remetida para venda fora do estabelecimento em operação com mercadoria sujeita ao regime de substituição tributária', 'Outro estado'),
    ('2551', 'Compra de bem para o ativo imobilizado', 'Outro estado'),
    ('2552', 'Transferência de bem do ativo imobilizado recebidos em transferência de outro estabelecimento da mesma empresa', 'Outro estado'),
    ('2553', 'Devolução de venda de bem do ativo imobilizado', 'Outro estado'),
    ('2554', 'Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento', 'Outro estado'),
    ('2555', 'Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento', 'Outro estado'),
    ('2556', 'Classificam-se neste código as compras de produtos destinadas ao uso ou consumo do estabelecimento', 'Outro estado'),
    ('2557', 'Transferência de material para uso ou consumo recebidos em transferência de outro estabelecimento da mesma empresa', 'Outro estado'),
    ('2904', 'Retorno de remessa para venda fora do estabelecimento', 'Outro estado'),
    ('2906', 'Retorno de mercadoria remetida para depósito fechado ou armazém geral', 'Outro estado'),
    ('2907', 'Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral', 'Outro estado'),
    ('2908', 'Entrada de bem por conta de contrato de comodato', 'Outro estado'),
    ('2909', 'Retorno de bem remetido por conta de contrato de comodato', 'Outro estado'),
    ('2912', 'Entrada de mercadoria ou bem recebido para demonstração ou mostruário', 'Outro estado'),
    ('2913', 'Retorno de mercadoria ou bem remetido para demonstração, mostruário ou treinamento', 'Outro estado'),
    ('2914', 'Retorno de mercadoria ou bem remetido para exposição ou feira', 'Outro estado'),
    ('2915', 'Entrada de mercadoria ou bem recebido para conserto ou reparo', 'Outro estado'),
    ('2916', 'Retorno de mercadoria ou bem remetido para conserto ou reparo', 'Outro estado'),
    ('2917', 'Entrada de mercadoria recebida em consignação mercantil ou industrial', 'Outro estado'),
    ('2918', 'Devolução de mercadoria remetida em consignação mercantil ou industrial', 'Outro estado'),
    ('2925', 'Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente', 'Outro estado'),
    ('2949', 'Outra entrada de mercadoria ou prestação de serviço não especificada', 'Outro estado'),
    ('5101', 'Venda de produção do estabelecimento', 'Mesmo estado'),
    ('5102', 'Venda de mercadoria adquirida ou recebida de terceiros', 'Mesmo estado'),
    ('5103', 'Venda de produção do estabelecimento ao contribuinte do ICMS', 'Mesmo estado'),
    ('5104', 'Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento', 'Mesmo estado'),
    ('5110', 'Venda de mercadoria, adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comercio, de que trata o Anexo do Convênio SINIEF s/n, de 15 de dezembro de 1970, que dispõe sobre o Sistema Nacional Integrado de Informações Econômico-Fiscais', 'Mesmo estado'),
    ('5114', 'Venda de mercadoria adquirida ou recebida de terceiros REMETIDA anteriormente em consignação mercantil', 'Mesmo estado'),
    ('5115', 'Venda de mercadoria adquirida ou recebida de terceiros, RECEBIDA anteriormente em consignação mercantil', 'Mesmo estado'),
    ('5117', 'Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura', 'Mesmo estado'),
    ('5119', 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem', 'Mesmo estado'),
    ('5120', 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem', 'Mesmo estado'),
    ('5123', 'Venda de mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente', 'Mesmo estado'),
    ('5202', 'Devolução de compra para comercialização', 'Mesmo estado'),
    ('5206', 'Anulação de valor relativo a aquisição de serviço de transporte', 'Mesmo estado'),
    ('5209', 'Devolução de produtos recebidas em transferência de outro estabelecimento da mesma empresa, para serem comercializadas', 'Mesmo estado'),
    ('5210', 'Devolução de compra para utilização na prestação de serviço', 'Mesmo estado'),
    ('5403', 'Venda de mercadoria, adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte-substituto', 'Mesmo estado'),
    ('5405', 'Venda de mercadoria, adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte-substituído', 'Mesmo estado'),
    ('5409', 'Transferência de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária', 'Mesmo estado'),
    ('5411', 'Devolução de compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária', 'Mesmo estado'),
    ('5412', 'Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita ao regime de substituição tributária', 'Mesmo estado'),
    ('5413', 'Devolução de mercadoria destinada ao uso ou consumo, em operação com mercadoria sujeita ao regime de substituição tributária', 'Mesmo estado'),
    ('5415', 'Remessa de mercadoria adquirida ou recebida de terceiros para venda fora do estabelecimento, em operação com mercadoria sujeita ao regime de substituição tributária', 'Mesmo estado'),
    ('5551', 'Venda de bem do ativo imobilizado', 'Mesmo estado'),
    ('5552', 'Transferência de bem do ativo imobilizado', 'Mesmo estado'),
    ('5553', 'Devolução de compra de bem para o ativo imobilizado', 'Mesmo estado'),
    ('5554', 'Remessa de bem do ativo imobilizado para uso fora do estabelecimento', 'Mesmo estado'),
    ('5555', 'Devolução de bem do ativo imobilizado de terceiro, recebido para uso no estabelecimento', 'Mesmo estado'),
    ('5556', 'Devolução de compra de material de uso ou consumo', 'Mesmo estado'),
    ('5557', 'Transferência de material de uso ou consumo', 'Mesmo estado'),
    ('5603', 'Ressarcimento de ICMS retido por substituição tributária', 'Mesmo estado'),
    ('5606', 'Utilização de saldo credor do ICMS para extinção por compensação de débitos fiscais', 'Mesmo estado'),
    ('5901', 'Remessa para industrialização', 'Mesmo estado'),
    ('5904', 'Remessa para venda fora do estabelecimento', 'Mesmo estado'),
    ('5905', 'Remessa para depósito fechado ou armazém geral', 'Mesmo estado'),
    ('5908', 'Remessa de bem por conta de contrato de comodato', 'Mesmo estado'),
    ('5909', 'Retorno de bem recebido por conta de contrato de comodato', 'Mesmo estado'),
    ('5910', 'Remessa em bonificação, doação ou brinde', 'Mesmo estado'),
    ('5911', 'Remessa de amostra grátis', 'Mesmo estado'),
    ('5912', 'Remessa de mercadoria ou bem para demonstração, mostruário ou treinamento', 'Mesmo estado'),
    ('5913', 'Retorno de mercadoria ou bem recebido para demonstração ou mostruário', 'Mesmo estado'),
    ('5914', 'Remessa de mercadoria ou bem para exposição ou feira', 'Mesmo estado'),
    ('5915', 'Remessa de mercadoria ou bem para conserto ou reparo', 'Mesmo estado'),
    ('5916', 'Retorno de mercadoria ou bem recebido para conserto ou reparo', 'Mesmo estado'),
    ('5917', 'Remessa de mercadoria em consignação mercantil ou industrial', 'Mesmo estado'),
    ('5918', 'Devolução de mercadoria recebida em consignação mercantil ou industrial', 'Mesmo estado'),
    ('5919', 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial', 'Mesmo estado'),
    ('5921', 'Devolução de vasilhame ou sacaria', 'Mesmo estado'),
    ('5922', 'Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura', 'Mesmo estado'),
    ('5927', 'Lançamento efetuado a título de baixa de estoque decorrente de perda, roubo ou deterioração', 'Mesmo estado'),
    ('5928', 'Lançamento efetuado a título de baixa de estoque decorrente do encerramento da atividade da empresa', 'Mesmo estado'),
    ('5929', 'Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também registrada em equipamento Emissor de Cupom Fiscal – ECF', 'Mesmo estado'),
    ('5949', 'Outra saída de mercadoria ou prestação de serviço não especificado', 'Mesmo estado'),
    ('6102', 'Venda de mercadoria adquirida ou recebida de terceiros', 'Outro estado'),
    ('6104', 'Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento', 'Outro estado'),
    ('6108', 'Venda de mercadoria adquirida ou recebida de terceiros, destinada a não contribuinte', 'Outro estado'),
    ('6110', 'Venda de mercadoria, adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', 'Outro estado'),
    ('6114', 'Venda de mercadoria adquirida ou recebida de terceiros REMETIDA anteriormente em consignação mercantil', 'Outro estado'),
    ('6115', 'Venda de mercadoria adquirida ou recebida de terceiros, RECEBIDA anteriormente em consignação mercantil', 'Outro estado'),
    ('6117', 'Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura', 'Outro estado'),
    ('6119', 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem', 'Outro estado'),
    ('6120', 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem', 'Outro estado'),
    ('6123', 'Venda de mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente', 'Outro estado'),
    ('6202', 'Devolução de compra para comercialização', 'Outro estado'),
    ('6206', 'Anulação de valor relativo a aquisição de serviço de transporte', 'Outro estado'),
    ('6209', 'Devolução de produtos recebidas em transferência de outro estabelecimento da mesma empresa, para serem comercializadas', 'Outro estado'),
    ('6210', 'Devolução de compra para utilização na prestação de serviço', 'Outro estado'),
    ('6403', 'Venda de mercadoria, adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte-substituto', 'Outro estado'),
    ('6404', 'Venda de mercadoria sujeita ao regime de substituição tributária, cujo imposto já tenha sido retido anteriormente', 'Outro estado'),
    ('6409', 'Transferência de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária', 'Outro estado'),
    ('6411', 'Devolução de compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária', 'Outro estado'),
    ('6412', 'Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita ao regime de substituição tributária', 'Outro estado'),
    ('6413', 'Devolução de mercadoria destinada ao uso ou consumo, em operação com mercadoria sujeita ao regime de substituição tributária', 'Outro estado'),
    ('6415', 'Remessa de mercadoria adquirida ou recebida de terceiros para venda fora do estabelecimento, em operação com mercadoria sujeita ao regime de substituição tributária', 'Outro estado'),
    ('6551', 'Venda de bem do ativo imobilizado', 'Outro estado'),
    ('6552', 'Transferência de bem do ativo imobilizado', 'Outro estado'),
    ('6553', 'Devolução de compra de bem para o ativo imobilizado', 'Outro estado'),
    ('6554', 'Remessa de bem do ativo imobilizado para uso fora do estabelecimento', 'Outro estado'),
    ('6555', 'Devolução de bem do ativo imobilizado de terceiro, recebido para uso no estabelecimento', 'Outro estado'),
    ('6556', 'Devolução de compra de material de uso ou consumo', 'Outro estado'),
    ('6557', 'Transferência de material de uso ou consumo', 'Outro estado'),
    ('6603', 'Ressarcimento de ICMS retido por substituição tributária', 'Outro estado'),
    ('6904', 'Remessa para venda fora do estabelecimento', 'Outro estado'),
    ('6905', 'Remessa para depósito fechado ou armazém geral', 'Outro estado'),
    ('6908', 'Remessa de bem por conta de contrato de comodato', 'Outro estado'),
    ('6909', 'Retorno de bem recebido por conta de contrato de comodato', 'Outro estado'),
    ('6910', 'Remessa em bonificação, doação ou brinde', 'Outro estado'),
    ('6911', 'Remessa de amostra grátis', 'Outro estado'),
    ('6912', 'Remessa de mercadoria ou bem para demonstração, mostruário ou treinamento', 'Outro estado'),
    ('6913', 'Retorno de mercadoria ou bem recebido para demonstração ou mostruário', 'Outro estado'),
    ('6914', 'Remessa de mercadoria ou bem para exposição ou feira', 'Outro estado'),
    ('6915', 'Remessa de mercadoria ou bem para conserto ou reparo', 'Outro estado'),
    ('6916', 'Retorno de mercadoria ou bem recebido para conserto ou reparo', 'Outro estado'),
    ('6917', 'Remessa de mercadoria em consignação mercantil ou industrial', 'Outro estado'),
    ('6918', 'Devolução de mercadoria recebida em consignação mercantil ou industrial', 'Outro estado'),
    ('6919', 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial', 'Outro estado'),
    ('6921', 'Devolução de vasilhame ou sacaria', 'Outro estado'),
    ('6922', 'Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura', 'Outro estado'),
    ('6929', 'Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também registrada em equipamento Emissor de Cupom Fiscal – ECF', 'Outro estado'),
    ('6949', 'Outra saída de mercadoria ou prestação de serviço não especificado', 'Outro estado'),
    ('7101', 'Venda de produção do estabelecimento', 'Exterior'),
    ('7102', 'Venda de mercadoria adquirida ou recebida de terceiros', 'Exterior'),
    ('7103', 'Venda de produção do estabelecimento ao contribuinte do ICMS', 'Exterior'),
    ('7104', 'Venda de produção do estabelecimento a não contribuinte', 'Exterior'),
    ('7901', 'Remessa para industrialização', 'Exterior')
ON CONFLICT (code) DO NOTHING;
