ALTER TABLE IF EXISTS nfe_product_config
    ADD COLUMN IF NOT EXISTS icms_rate DECIMAL(5,4) DEFAULT 0.1700,
    ADD COLUMN IF NOT EXISTS pis_rate DECIMAL(5,4) DEFAULT 0.0165,
    ADD COLUMN IF NOT EXISTS cofins_rate DECIMAL(5,4) DEFAULT 0.0760,
    ADD COLUMN IF NOT EXISTS natureza_op TEXT;
